### ISSUE TITLE
Corrupt ODIM conversion when rapic moments within tilt have differing range bin counts

### ISSUE THREAD

**Issue by marack** [bom-radar/rapic#1]
As reported by JS, the attached rapic scan produced corrupted VRAD and WRAD moments when converted to ODIM using the `rapic_to_odim` converter utility.

[201512152330Kurnell.rapic.zip](https://github.com/bom-radar/rapic/files/127234/201512152330Kurnell.rapic.zip)

Preliminary analysis reveals the corruption occurs only when the moments of a rapic tilt are sent with differing numbers of range bins.  In the attached case the doppler moments contain fewer range bins that the reflectivity moment.

**Comment by marack** [comment]
Problem was caused by incorrectly referencing moment bin count during odim conversion when tilt bin count (max of all moment bin counts) was intended.  This regression was introduced during the activity to remove the dependency on the Rainfields 3 utility library (`rainutil`).

Tested against rapic file attached to issue.  Correct conversion is now observed.

**Comment by joshua-wx** [comment]
Thanks marack, much appreciate the quick response. Tested on my end and everything is working fine :+1:
