### ISSUE TITLE
Ignored return value warning during compilation

### ISSUE THREAD

**Issue by marack** [bom-radar/rapic#2]
Originally reported by JS.  Some compiler / standard library combinations produce a warning about ignoring the return value of the `write` function.  These warnings are only relevant to the ROWLF server client class and have no impact on other functions such as rapic to ODIM conversion.  See below for example warning text:

```
[ 33%] Building CXX object CMakeFiles/rapic.dir/rapic.cc.o
/home/meso/bom-radar-utility/rapic/rapic.cc: In member function ‘bool rapic::client::process_traffic()’:
/home/meso/bom-radar-utility/rapic/rapic.cc:729:60: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
     write(socket_, msg_connect.c_str(), msg_connect.size());
                                                            ^
/home/meso/bom-radar-utility/rapic/rapic.cc:733:52: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
       write(socket_, filter.c_str(), filter.size());
                                                    ^
/home/meso/bom-radar-utility/rapic/rapic.cc:739:64: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
     write(socket_, msg_keepalive.c_str(), msg_keepalive.size());
```

**Comment by joshua-wx** [comment]
Here's a little more info on my compiler and system

~/Dropbox/PhD/Code/rapic_to_pyart_notebooks$ gcc -v 
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.4-2ubuntu1~14.04.1' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.1)

**Comment by joshua-wx** [comment]
No more error messages! Thanks :beers:
